version: '2'
services:
  my-db:
    image: mysql:latest
    environment:
      - MYSQL_DB=pro_php
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '33306:3306'
  my-fw:
    build: ./php
    ports:
      - '8000:80'
    volumes:
      - ../application:/var/www/html
    depends_on:
      - my-db
volumes:
  my-db:
